name: Android Build with Expo

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'shared/**'
      - 'app.json'
      - 'App.js'
      - 'metro.config.js'
      - 'babel.config.js'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: |
        npm ci
        npm install --legacy-peer-deps expo expo-cli @expo/webpack-config expo-dev-client expo-updates
        npm install -g eas-cli
        
    - name: Login to Expo
      run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
      
    - name: Build Android APK
      run: |
        npx eas build --platform android --profile preview --non-interactive
        
    # Add steps to download and distribute the APK
    # These would depend on your specific distribution needs